/*
 * This source file was generated by the Gradle 'init' task
 */
package com.edoardoconti.mfs.app;

import javafx.application.Application;
import javafx.stage.Stage;

import com.edoardoconti.mfs.app.components.AppStrings;

public class App extends Application {
    public static void main(String[] args) {
        //System.out.println("Hello, Modular Furniture System!");
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {

        var guiAppController = new GUIAppController(primaryStage);

        primaryStage.setTitle(AppStrings.APP_NAME);
        primaryStage.setScene(guiAppController.getScene());
        primaryStage.setResizable(false);
        primaryStage.show();
    }
}
